### ISSUE TITLE
errors with django 3 so limit to django 2 or fix them

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/django-peeringdb#37]
Got:

> django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.

with django 3.  Limiting to django 2 with:

> pip install "django<3"

made the problem go away.  requirements-django.txt may need similar, or issues with django 3 need to be fixed.

**Comment by grizz** [comment]
Hrm, it passes all the tests with django 3, we think that's something from the peeringdb client.

**Comment by paravoid** [comment]
With:
- Django==3.0.5
- django-handleref==0.5.0
- peeringdb==1.0.0
- django-peeringdb==2.0.0

And after running "peeringdb sync", I get the following backtrace:
```
  File "/venv/lib/python3.7/site-packages/peeringdb/backend.py", line 26, in wrapped
    return fn(*args, **kwargs)
  File "/venv/lib/python3.7/site-packages/django_peeringdb/client_adaptor/backend.py", line 89, in last_change
    upd = concrete.handleref.last_change()
  File "/venv/lib/python3.7/site-packages/django_handleref/manager.py", line 101, in last_change 
    return self.get_queryset().last_change(**kwargs)
  File "/venv/lib/python3.7/site-packages/django_handleref/manager.py", line 23, in last_change
    cdt = self.latest('created')
  File "/venv/lib/python3.7/site-packages/django/db/models/query.py", line 660, in latest
    return self.reverse()._earliest(*fields)
  File "/venv/lib/python3.7/site-packages/django/db/models/query.py", line 654, in _earliest
    return obj.get()
  File "/venv/lib/python3.7/site-packages/django/db/models/query.py", line 411, in get
    num = len(clone)
  File "/venv/lib/python3.7/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "/venv/lib/python3.7/site-packages/django/db/models/query.py", line 1261, in _fetch_all 
    self._result_cache = list(self._iterable_class(self))
  File "/venv/lib/python3.7/site-packages/django/db/models/query.py", line 74, in __iter__
    for row in compiler.results_iter(results):
  File "/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1095, in apply_converters
    value = converter(value, expression, connection)
TypeError: from_db_value() missing 1 required positional argument: 'context'
```

**Comment by ccaputo** [comment]
I am having success with:

```
$ peeringdb --version
peeringdb 1.0.0.1

$ django-admin --version
2.2.9
```

Can you make sure you are at those revs or higher and test again?

**Comment by paravoid** [comment]
Not sure what you mean -- you seem to have Django 2.2.9 installed, but this issue is about incompatibilities with Django 3.x versions. It indeed works fine here with 2.2.12, the issue presents when I upgrade to 3.0.5.

**Comment by ccaputo** [comment]
Apology.  I'm actually am running Django 2.2.12 also.
